version: '3'
services:
  app:
    container_name: firstapp
    environment:
     - MONGO_URL=mongo
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 80:3000
    links:
      - mongo
    command: npm run prod

  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=firstapp_db
    ports:
      - '27017:27017'

